export const NOT_APPLICABLE_ERROR= 1;
export const NO_QUESTIONS_ERROR = 2;
export const NOT_ENOUGH_ANSWERS_ERROR=3;
export const NUMBER_OF_CORRECT_ANSWERS_OTHER_THAN_ONE_ERROR=4;
export const MULTIPLE_ANSWERS_WITH_SAME_ORDER_ERROR=5;
export const NOT_CONSISTENT_ORDER_NUMBERS=6;